### ISSUE TITLE
Crashing when entering regions with pop up enabled

### ISSUE THREAD

**Issue by Shahelion** [brandyyn/Kingdom-Regions#3]
5.8: [crash-2024-11-11_07.17.14-client.txt](https://github.com/user-attachments/files/17704318/crash-2024-11-11_07.17.14-client.txt)
5.7: [crash-2024-11-11_07.22.28-client.txt](https://github.com/user-attachments/files/17704319/crash-2024-11-11_07.22.28-client.txt)

These are both without Angelica.

**Comment by brandyyn** [comment]
should be fixed
