### ISSUE TITLE
Repeating pop-ups don't repeat until a different one triggers

### ISSUE THREAD

**Issue by Shahelion** [brandyyn/Kingdom-Regions#4]
Title is probably confusing. What I mean is, let's say I have titles set for Dark Forest and Twilight Swamp, but NOT for Twilight Stream.

If I enter either the Dark Forest or the Twilight Swamp, the name pops up. If I enter the Stream, but then go back into the same biome, even though I changed biomes, the name doesn't pop up again. However, if I go into the swamp, THEN back to the forest, both work as they should.

It seems that once a given biome name has appeared, it won't reappear after leaving and re-entering that biome unless the player enters another biome that has a pop-up.

Hopefully that makes sense.

**Comment by brandyyn** [comment]
fixed :)
